apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iris-tls
  namespace: iris
spec:
  secretName: iris-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - app.iris.calebache.com
